# Generated by Django 3.2.4 on 2021-07-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_take_attendence_attendence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bloodgroup',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
